// <auto-generated>
// D-Drive: 自動生成ファイル。手編集禁止。
// D-Drive/Tools/Generate/Regenerate Tuning Keys から再生成される。
// </auto-generated>

namespace DDrive.Generated
{
    public static class TUNING
    {
        public const string PlayerHP = "Player/HP";
        public const string PlayerSpeed = "Player/Speed";
    }

    public static class TUNING_TABLE
    {
        public const string EnemyParams = "EnemyParams";
    }

    public static class TUNING_COLUMN
    {
        public const string EnemyParamsHp = "Hp";
    }
}
