using System;
using System.Collections.Generic;
using System.IO;
using System.Text.RegularExpressions;
using DDrive.Editor.Codegen;
using DDrive.Runtime.Tuning;
using NUnit.Framework;
using UnityEditor;
using UnityEngine;

namespace DDrive.Tests.Editor.Compat
{
    // [42_distribution.md] §5.7 / §5.11-7(P-3、2026-09-20) — 生成コード(`AssetIds.g.cs`/`Tuning.g.cs`)の
    // 出力形式(クラス名・名前空間・命名規則・`static readonly`/`const` の形)を固定する。
    //
    // Tuning.g.cs: 入力(TuningTable.Entries/Tables)が GUID に依存しない文字列キーのみなので、
    // 完全な全文一致のゴールデンにできる(実際に §5.11 が要求する「固定のカタログ入力に対する生成結果の
    // ゴールデン」そのもの)。
    //
    // AssetIds.g.cs: 各エントリの ulong 値は `StableHashFromGuid(guid)` で GUID(Unity が
    // `AssetDatabase.CreateAsset` 時に採番する乱数)に依存するため、値そのものを固定した全文ゴールデンには
    // できない(GUID を手で指定する公開 API が無く、.meta の手編集は禁止 — CLAUDE.md §0-1)。
    // 代わりに「生成された行の**形**(ヘッダコメント・using・namespace・クラス宣言・
    // `public static readonly AssetId<Marker> 定数名 = new(0x...UL, AssetType.X);` という 1 行の構文)が
    // 変わっていないこと」を、実際に採番された GUID から独立に再計算した期待値と突き合わせて検証する
    // (IdHashGoldenTests が算法そのものを別途固定しているため、ここでの目的は「形」の固定)。
    public class CodegenGoldenTests
    {
        private const string TempDir = TestTempFolder.Root + "/Temp";
        private readonly List<string> _createdAssetPaths = new();
        private string _tempOutputPath;

        [SetUp]
        public void SetUp()
        {
            if (!AssetDatabase.IsValidFolder(TempDir))
            {
                TestTempFolder.CreateFolder("Temp");
            }

            _tempOutputPath = Path.Combine(Path.GetTempPath(), "ddrive_test_codegen_" + Guid.NewGuid().ToString("N") + ".cs");
        }

        [TearDown]
        public void TearDown()
        {
            foreach (var path in _createdAssetPaths)
            {
                if (AssetDatabase.LoadAssetAtPath<TestAssetData>(path) != null)
                {
                    AssetDatabase.DeleteAsset(path);
                }
            }

            _createdAssetPaths.Clear();

            if (File.Exists(_tempOutputPath))
            {
                File.Delete(_tempOutputPath);
            }
        }

        [Test]
        public void TuningCodegen_FixedInput_MatchesFullTextGolden()
        {
            var table = ScriptableObject.CreateInstance<TuningTable>();
            table.Entries = new[]
            {
                new TuningEntry { Key = "Player/HP", Type = TuningValueType.Int, ValueInt = 100 },
                new TuningEntry { Key = "Player/Speed", Type = TuningValueType.Float, ValueFloat = 5f },
            };
            table.Tables = new[]
            {
                new TuningTableEntry
                {
                    Key = "EnemyParams",
                    Columns = new[] { new TuningTableColumn { Key = "Hp", Type = TuningValueType.Int } },
                    Rows = Array.Empty<TuningTableRow>(),
                },
            };

            try
            {
                var result = TuningCodegen.Regenerate(table, _tempOutputPath);
                Assert.IsTrue(result.Success);

                var actual = File.ReadAllText(_tempOutputPath).Replace("\r\n", "\n");
                CompatGoldenAssert.AssertMatches(
                    DDrive.Editor.Compat.CompatSnapshotPaths.TuningCodegen,
                    actual,
                    "生成コード(Tuning.g.cs)のクラス名・命名規則・形の変更は MAJOR([42] §5.7)。定数の増減のみなら MINOR。");
            }
            finally
            {
                UnityEngine.Object.DestroyImmediate(table);
            }
        }

        [Test]
        public void AssetIdGenerator_OutputShape_MatchesExpectedFormat()
        {
            var data = ScriptableObject.CreateInstance<TestAssetData>();
            const string fileName = "SE_Codegen_ShapeCheck";
            var path = $"{TempDir}/{fileName}.asset";
            AssetDatabase.CreateAsset(data, path);
            _createdAssetPaths.Add(path);
            using (DDrive.Editor.Versioning.VersionStampSuppression.Scope())
            {
                AssetDatabase.SaveAssets();
            }

            var guid = AssetDatabase.AssetPathToGUID(path);
            var expectedId = AssetIdGenerator.StableHashFromGuid(guid);

            var result = AssetIdGenerator.Regenerate(_tempOutputPath, includeTestAssemblies: true);
            Assert.IsTrue(result.Success);
            var generated = File.ReadAllText(_tempOutputPath);

            StringAssert.Contains("// <auto-generated>", generated);
            StringAssert.Contains("using DDrive.Foundation.Identity;", generated);
            StringAssert.Contains("namespace DDrive.Generated", generated);
            StringAssert.Contains("public static class DDRIVE_TEST_ID", generated);

            var expectedLine = $"public static readonly AssetId<DDrive.Tests.Editor.TestAssetMarker> CodegenShapeCheck = new(0x{expectedId:X}UL, AssetType.Se);";
            StringAssert.Contains(expectedLine, generated,
                "AssetIds.g.cs の 1 行の構文(修飾子・型・定数名の形・16進数フォーマット・末尾のセミコロン)が変わりました([42] §5.7、MAJOR)。");

            // クラス本体が波括弧で閉じている・生成順が「クラスごとにブロック」になっている等、大枠の構造も崩れていないことを確認する。
            Assert.IsTrue(Regex.IsMatch(generated, @"public static class DDRIVE_TEST_ID\s*\{[\s\S]*?\}", RegexOptions.Multiline),
                "定数クラスのブロック構造が変わりました。");
        }
    }
}
