using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Text;
using DDrive.Editor.Menu;
using DDrive.Editor.Versioning;
using DDrive.Foundation.Data;
using DDrive.Foundation.Identity;
using UnityEditor;
using UnityEngine;

namespace DDrive.Editor.Codegen
{
    // AssetDataBase 派生の全アセットを走査し、未割当の Id(ulong)を GUID から確定させたうえで
    // 種別ごとの ID 定数クラスを Assets/Generated/AssetIds.g.cs に書き出す。
    // Id は GUID 由来で決まるため、再実行は冪等でありアセットのリネームでも不変。
    public static class AssetIdGenerator
    {
        public const string DefaultOutputPath = "Assets/Generated/AssetIds.g.cs";

        public readonly struct Duplicate
        {
            public readonly string PathA;
            public readonly string PathB;
            public readonly ulong Id;

            public Duplicate(string pathA, string pathB, ulong id)
            {
                PathA = pathA;
                PathB = pathB;
                Id = id;
            }
        }

        public sealed class Result
        {
            public int TotalCount;
            public int AssignedCount;
            public readonly List<Duplicate> Duplicates = new();
            public bool Success => Duplicates.Count == 0;
        }

        private struct Definition
        {
            public Type DataType;
            public AssetType AssetType;
            public Type MarkerType;
            public string ConstantsClassName;
        }

        [MenuItem(DDriveMenu.Generate + "Regenerate Asset IDs")]
        public static void RegenerateMenuItem()
        {
            var result = Regenerate();
            if (result.Success)
            {
                Debug.Log($"[DDrive] AssetIds regenerated: {result.TotalCount} entries, {result.AssignedCount} newly assigned.");
            }
        }

        // includeTestAssemblies: テスト asmdef(DDrive.Tests.*)内の Data 型も走査するか。
        // メニューからの通常再生成では除外する(生成物に DUMMYID 等のテスト用クラスを残さないため。2026-09-08)。
        // AssetIdGeneratorTests はテスト用の型で検証するため true で呼ぶ。
        public static Result Regenerate(string outputPath = DefaultOutputPath, bool includeTestAssemblies = false)
        {
            // [11_tasks.md] 6-3: ID 再生成は「一括処理」の一種なので、未発行だった ID を確定させるだけで
            // Version を上げない(対象になり得る全 Data が一度に対象になり、ノイズになるため)。
            using var _versionStampScope = VersionStampSuppression.Scope();

            var result = new Result();
            var definitions = FindDefinitions(includeTestAssemblies);
            var seenIds = new Dictionary<ulong, string>();
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// D-Drive: 自動生成ファイル。手編集禁止。");
            sb.AppendLine("// D-Drive/Tools/Regenerate Asset IDs から再生成される。");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using DDrive.Foundation.Identity;");
            sb.AppendLine();
            sb.AppendLine("namespace DDrive.Generated");
            sb.AppendLine("{");

            foreach (var def in definitions)
            {
                var entries = new List<(string constName, ulong id)>();
                var guids = AssetSearch.FindAssets("t:" + def.DataType.Name);

                foreach (var guid in guids)
                {
                    var path = AssetDatabase.GUIDToAssetPath(guid);
                    var asset = AssetDatabase.LoadAssetAtPath(path, def.DataType) as AssetDataBase;
                    if (asset == null || asset.GetType() != def.DataType)
                    {
                        continue;
                    }

                    if (asset.Id == 0)
                    {
                        asset.Id = StableHashFromGuid(guid);
                        EditorUtility.SetDirty(asset);
                        result.AssignedCount++;
                    }

                    if (seenIds.TryGetValue(asset.Id, out var otherPath) && otherPath != path)
                    {
                        result.Duplicates.Add(new Duplicate(otherPath, path, asset.Id));
                    }
                    else
                    {
                        seenIds[asset.Id] = path;
                    }

                    // 定数名は必ずファイル名(ツールが規約生成した SE_Category_Identifier 形式)から作る。
                    // DisplayName は日本語等の自由入力(FR-1.5)であり、C# 識別子の材料にしない。
                    var sourceName = Path.GetFileNameWithoutExtension(path);
                    entries.Add((ToConstantName(sourceName), asset.Id));
                    result.TotalCount++;
                }

                entries.Sort((a, b) => string.CompareOrdinal(a.constName, b.constName));

                sb.AppendLine($"    public static class {def.ConstantsClassName}");
                sb.AppendLine("    {");
                var usedNames = new HashSet<string>();
                foreach (var entry in entries)
                {
                    // 定数名の衝突(同名アセット等)は ID サフィックスで一意化し、生成コードの CS0102 を防ぐ。
                    var constName = entry.constName;
                    if (!usedNames.Add(constName))
                    {
                        constName = $"{constName}_{entry.id:X4}";
                        usedNames.Add(constName);
                    }

                    sb.AppendLine($"        public static readonly AssetId<{def.MarkerType.FullName}> {constName} = new(0x{entry.id:X}UL, AssetType.{def.AssetType});");
                }

                sb.AppendLine("    }");
                sb.AppendLine();
            }

            sb.AppendLine("}");

            if (!result.Success)
            {
                foreach (var d in result.Duplicates)
                {
                    Debug.LogError($"[DDrive] Duplicate AssetId 0x{d.Id:X} between '{d.PathA}' and '{d.PathB}'. Fix before regenerating.");
                }

                return result;
            }

            AssetDatabase.SaveAssets();

            var dir = Path.GetDirectoryName(outputPath);
            if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
            {
                Directory.CreateDirectory(dir);
            }

            File.WriteAllText(outputPath, sb.ToString());

            var normalized = outputPath.Replace('\\', '/');
            if (normalized.StartsWith("Assets/"))
            {
                AssetDatabase.ImportAsset(normalized);
            }

            return result;
        }

        private static List<Definition> FindDefinitions(bool includeTestAssemblies)
        {
            var list = new List<Definition>();

            foreach (var asm in AppDomain.CurrentDomain.GetAssemblies())
            {
                if (!includeTestAssemblies && asm.GetName().Name.StartsWith("DDrive.Tests", StringComparison.Ordinal))
                {
                    continue;
                }

                Type[] types;
                try
                {
                    types = asm.GetTypes();
                }
                catch (ReflectionTypeLoadException e)
                {
                    types = e.Types;
                }

                if (types == null)
                {
                    continue;
                }

                foreach (var t in types)
                {
                    if (t == null || t.IsAbstract || !typeof(AssetDataBase).IsAssignableFrom(t))
                    {
                        continue;
                    }

                    var attr = t.GetCustomAttribute<AssetIdDefinitionAttribute>();
                    if (attr == null)
                    {
                        continue;
                    }

                    list.Add(new Definition
                    {
                        DataType = t,
                        AssetType = attr.Type,
                        MarkerType = attr.MarkerType,
                        ConstantsClassName = attr.ConstantsClassName,
                    });
                }
            }

            return list;
        }

        // 2026-09-18(P-1, docs/42 §5.13/§7 A-6): 1.0.0 発効前の一度きりの例外として
        // MODEL/ANC/ANCG/SKIN を追加し、KnownPrefixes の不整合(定数名に接頭辞が残る)を解消した。
        // 発効後は本セットへの追加は禁止(追加すると既存の定数名が変わり互換性を破壊するため)。
        private static readonly HashSet<string> KnownPrefixes = new(StringComparer.OrdinalIgnoreCase)
        {
            "SE", "BGM", "VFX", "ANIM", "ANIM2D", "MAT", "TEX", "CANVAS", "PREFAB", "PRES", "SHAKE", "HAPTIC", "HAPTICS", "UITWEEN",
            "MODEL", "ANC", "ANCG", "SKIN",
            // [26_timeline.md] §4.1(6-10a、2026-09-18): CutsceneData の接頭辞。P 発効(P-13)前のため追加可能。
            "CUT",
        };

        // internal(同一 asmdef): 5-6 の CodeReferenceScan が「削除しようとしている ID の生成済み定数名」を
        // 同じ規則で再現するために公開する(定数名の生成ロジックを二重に持たないため)。
        internal static string ToConstantName(string rawName)
        {
            var tokens = rawName.Split(new[] { '_', '-', ' ' }, StringSplitOptions.RemoveEmptyEntries);
            var start = tokens.Length > 1 && KnownPrefixes.Contains(tokens[0]) ? 1 : 0;

            var sb = new StringBuilder();
            for (var i = start; i < tokens.Length; i++)
            {
                // C# 識別子に使えない文字(日本語・記号等)は除去する。素通しすると
                // 生成された AssetIds.g.cs がコンパイルエラーになり、プロジェクト全体が壊れる。
                var tok = SanitizeToken(tokens[i]);
                if (tok.Length == 0)
                {
                    continue;
                }

                sb.Append(char.ToUpperInvariant(tok[0]));
                if (tok.Length > 1)
                {
                    sb.Append(tok.Substring(1));
                }
            }

            if (sb.Length == 0)
            {
                sb.Append("Unnamed");
            }

            if (!char.IsLetter(sb[0]))
            {
                sb.Insert(0, '_');
            }

            return sb.ToString();
        }

        private static string SanitizeToken(string token)
        {
            var sb = new StringBuilder(token.Length);
            foreach (var c in token)
            {
                if (c is >= 'A' and <= 'Z' or >= 'a' and <= 'z' or >= '0' and <= '9')
                {
                    sb.Append(c);
                }
            }

            return sb.ToString();
        }

        // AssetCreationService(1-5) からも同じ規則で ID を発行するため public。
        public static ulong StableHashFromGuid(string guid)
        {
            const ulong fnvOffset = 14695981039346656037UL;
            const ulong fnvPrime = 1099511628211UL;

            var hash = fnvOffset;
            foreach (var c in guid)
            {
                hash ^= c;
                hash *= fnvPrime;
            }

            return hash == 0 ? 1 : hash;
        }
    }
}
