using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Text;
using DDrive.Editor.Menu;
using DDrive.Foundation.Data;
using DDrive.Foundation.Identity;
using UnityEditor;
using UnityEngine;

namespace DDrive.Editor.Codegen
{
    // AssetDataBase 派生の全アセットを走査し、未割当の Id(ulong)を GUID から確定させたうえで
    // 種別ごとの ID 定数クラスを Assets/Generated/AssetIds.g.cs に書き出す。
    // Id は GUID 由来で決まるため、再実行は冪等でありアセットのリネームでも不変。
    public static class AssetIdGenerator
    {
        public const string DefaultOutputPath = "Assets/Generated/AssetIds.g.cs";

        public readonly struct Duplicate
        {
            public readonly string PathA;
            public readonly string PathB;
            public readonly ulong Id;

            public Duplicate(string pathA, string pathB, ulong id)
            {
                PathA = pathA;
                PathB = pathB;
                Id = id;
            }
        }

        public sealed class Result
        {
            public int TotalCount;
            public int AssignedCount;
            public readonly List<Duplicate> Duplicates = new();
            public bool Success => Duplicates.Count == 0;
        }

        private struct Definition
        {
            public Type DataType;
            public AssetType AssetType;
            public Type MarkerType;
            public string ConstantsClassName;
        }

        [MenuItem(DDriveMenu.Generate + "Regenerate Asset IDs")]
        public static void RegenerateMenuItem()
        {
            var result = Regenerate();
            if (result.Success)
            {
                Debug.Log($"[DDrive] AssetIds regenerated: {result.TotalCount} entries, {result.AssignedCount} newly assigned.");
            }
        }

        public static Result Regenerate(string outputPath = DefaultOutputPath)
        {
            var result = new Result();
            var definitions = FindDefinitions();
            var seenIds = new Dictionary<ulong, string>();
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// D-Drive: 自動生成ファイル。手編集禁止。");
            sb.AppendLine("// D-Drive/Tools/Regenerate Asset IDs から再生成される。");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using DDrive.Foundation.Identity;");
            sb.AppendLine();
            sb.AppendLine("namespace DDrive.Generated");
            sb.AppendLine("{");

            foreach (var def in definitions)
            {
                var entries = new List<(string constName, ulong id)>();
                var guids = AssetDatabase.FindAssets("t:" + def.DataType.Name);

                foreach (var guid in guids)
                {
                    var path = AssetDatabase.GUIDToAssetPath(guid);
                    var asset = AssetDatabase.LoadAssetAtPath(path, def.DataType) as AssetDataBase;
                    if (asset == null || asset.GetType() != def.DataType)
                    {
                        continue;
                    }

                    if (asset.Id == 0)
                    {
                        asset.Id = StableHashFromGuid(guid);
                        EditorUtility.SetDirty(asset);
                        result.AssignedCount++;
                    }

                    if (seenIds.TryGetValue(asset.Id, out var otherPath) && otherPath != path)
                    {
                        result.Duplicates.Add(new Duplicate(otherPath, path, asset.Id));
                    }
                    else
                    {
                        seenIds[asset.Id] = path;
                    }

                    var sourceName = !string.IsNullOrEmpty(asset.DisplayName)
                        ? asset.DisplayName
                        : Path.GetFileNameWithoutExtension(path);
                    entries.Add((ToConstantName(sourceName), asset.Id));
                    result.TotalCount++;
                }

                entries.Sort((a, b) => string.CompareOrdinal(a.constName, b.constName));

                sb.AppendLine($"    public static class {def.ConstantsClassName}");
                sb.AppendLine("    {");
                foreach (var entry in entries)
                {
                    sb.AppendLine($"        public static readonly AssetId<{def.MarkerType.FullName}> {entry.constName} = new(0x{entry.id:X}UL, AssetType.{def.AssetType});");
                }

                sb.AppendLine("    }");
                sb.AppendLine();
            }

            sb.AppendLine("}");

            if (!result.Success)
            {
                foreach (var d in result.Duplicates)
                {
                    Debug.LogError($"[DDrive] Duplicate AssetId 0x{d.Id:X} between '{d.PathA}' and '{d.PathB}'. Fix before regenerating.");
                }

                return result;
            }

            AssetDatabase.SaveAssets();

            var dir = Path.GetDirectoryName(outputPath);
            if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
            {
                Directory.CreateDirectory(dir);
            }

            File.WriteAllText(outputPath, sb.ToString());

            var normalized = outputPath.Replace('\\', '/');
            if (normalized.StartsWith("Assets/"))
            {
                AssetDatabase.ImportAsset(normalized);
            }

            return result;
        }

        private static List<Definition> FindDefinitions()
        {
            var list = new List<Definition>();

            foreach (var asm in AppDomain.CurrentDomain.GetAssemblies())
            {
                Type[] types;
                try
                {
                    types = asm.GetTypes();
                }
                catch (ReflectionTypeLoadException e)
                {
                    types = e.Types;
                }

                if (types == null)
                {
                    continue;
                }

                foreach (var t in types)
                {
                    if (t == null || t.IsAbstract || !typeof(AssetDataBase).IsAssignableFrom(t))
                    {
                        continue;
                    }

                    var attr = t.GetCustomAttribute<AssetIdDefinitionAttribute>();
                    if (attr == null)
                    {
                        continue;
                    }

                    list.Add(new Definition
                    {
                        DataType = t,
                        AssetType = attr.Type,
                        MarkerType = attr.MarkerType,
                        ConstantsClassName = attr.ConstantsClassName,
                    });
                }
            }

            return list;
        }

        private static readonly HashSet<string> KnownPrefixes = new(StringComparer.OrdinalIgnoreCase)
        {
            "SE", "BGM", "VFX", "ANIM", "ANIM2D", "MAT", "TEX", "CANVAS", "PREFAB", "PRES", "SHAKE", "HAPTIC", "HAPTICS", "UITWEEN",
        };

        private static string ToConstantName(string rawName)
        {
            var tokens = rawName.Split(new[] { '_', '-', ' ' }, StringSplitOptions.RemoveEmptyEntries);
            var start = tokens.Length > 1 && KnownPrefixes.Contains(tokens[0]) ? 1 : 0;

            var sb = new StringBuilder();
            for (var i = start; i < tokens.Length; i++)
            {
                var tok = tokens[i];
                sb.Append(char.ToUpperInvariant(tok[0]));
                if (tok.Length > 1)
                {
                    sb.Append(tok.Substring(1));
                }
            }

            if (sb.Length == 0)
            {
                sb.Append("Unnamed");
            }

            if (!char.IsLetter(sb[0]))
            {
                sb.Insert(0, '_');
            }

            return sb.ToString();
        }

        private static ulong StableHashFromGuid(string guid)
        {
            const ulong fnvOffset = 14695981039346656037UL;
            const ulong fnvPrime = 1099511628211UL;

            var hash = fnvOffset;
            foreach (var c in guid)
            {
                hash ^= c;
                hash *= fnvPrime;
            }

            return hash == 0 ? 1 : hash;
        }
    }
}
