using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using DDrive.Editor.Menu;
using DDrive.Editor.Spec;
using DDrive.Runtime.Tuning;
using UnityEditor;
using UnityEngine;

namespace DDrive.Editor.Codegen
{
    // [27_spec_sheet.md] §3.2 / [11_tasks.md] 5-13 — TuningTable.Entries から
    // Assets/Generated/Tuning.g.cs の TUNING.キー定数を生成する(AssetIdGenerator と同じ考え方:
    // コードからは文字列リテラルを直書きせず、生成された定数だけを使う)。
    public static class TuningCodegen
    {
        public const string DefaultOutputPath = "Assets/Generated/Tuning.g.cs";

        public sealed class Result
        {
            public int TotalCount;
            public bool Success = true;
        }

        [MenuItem(DDriveMenu.Generate + "Regenerate Tuning Keys")]
        public static void RegenerateMenuItem()
        {
            var result = Regenerate();
            Debug.Log($"[DDrive] Tuning keys regenerated: {result.TotalCount} entries.");
        }

        public static Result Regenerate(TuningTable table = null, string outputPath = DefaultOutputPath)
        {
            table ??= ResolveDefaultTable();
            var result = new Result();

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// D-Drive: 自動生成ファイル。手編集禁止。");
            sb.AppendLine("// D-Drive/Tools/Generate/Regenerate Tuning Keys から再生成される。");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("namespace DDrive.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    public static class TUNING");
            sb.AppendLine("    {");

            if (table != null && table.Entries != null)
            {
                var usedNames = new HashSet<string>();
                var sortedKeys = new List<string>();
                foreach (var entry in table.Entries)
                {
                    if (!string.IsNullOrEmpty(entry.Key))
                    {
                        sortedKeys.Add(entry.Key);
                    }
                }

                sortedKeys.Sort(StringComparer.Ordinal);

                foreach (var key in sortedKeys)
                {
                    var constName = ToConstantName(key);
                    if (!usedNames.Add(constName))
                    {
                        continue; // 重複キーは SpecSheetParser 側で衝突として検出済みのため、生成側では単に無視する
                    }

                    sb.AppendLine($"        public const string {constName} = \"{key}\";");
                    result.TotalCount++;
                }
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            var dir = Path.GetDirectoryName(outputPath);
            if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
            {
                Directory.CreateDirectory(dir);
            }

            File.WriteAllText(outputPath, sb.ToString());

            var normalized = outputPath.Replace('\\', '/');
            if (normalized.StartsWith("Assets/"))
            {
                AssetDatabase.ImportAsset(normalized);
            }

            return result;
        }

        private static TuningTable ResolveDefaultTable()
        {
            var settings = DDriveSpecSettings.Load();
            if (settings != null && settings.TuningTable != null)
            {
                return settings.TuningTable;
            }

            return AssetDatabase.LoadAssetAtPath<TuningTable>(DDriveSpecSettings.DefaultTuningTablePath);
        }

        private static string ToConstantName(string key)
        {
            var tokens = key.Split(new[] { '/', '_', '-', ' ' }, StringSplitOptions.RemoveEmptyEntries);
            var sb = new StringBuilder();
            foreach (var token in tokens)
            {
                var clean = SanitizeToken(token);
                if (clean.Length == 0)
                {
                    continue;
                }

                sb.Append(char.ToUpperInvariant(clean[0]));
                if (clean.Length > 1)
                {
                    sb.Append(clean.Substring(1));
                }
            }

            if (sb.Length == 0)
            {
                sb.Append("Unnamed");
            }

            if (!char.IsLetter(sb[0]))
            {
                sb.Insert(0, '_');
            }

            return sb.ToString();
        }

        private static string SanitizeToken(string token)
        {
            var sb = new StringBuilder(token.Length);
            foreach (var c in token)
            {
                if (c is >= 'A' and <= 'Z' or >= 'a' and <= 'z' or >= '0' and <= '9')
                {
                    sb.Append(c);
                }
            }

            return sb.ToString();
        }
    }
}
