using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using DDrive.Editor.Menu;
using DDrive.Editor.Spec;
using DDrive.Runtime.Tuning;
using UnityEditor;
using UnityEngine;

namespace DDrive.Editor.Codegen
{
    // [27_spec_sheet.md] §3.2 / [11_tasks.md] 5-13 — TuningTable.Entries から
    // Assets/Generated/Tuning.g.cs の TUNING.キー定数を生成する(AssetIdGenerator と同じ考え方:
    // コードからは文字列リテラルを直書きせず、生成された定数だけを使う)。
    public static class TuningCodegen
    {
        public const string DefaultOutputPath = "Assets/Generated/Tuning.g.cs";

        public sealed class Result
        {
            public int TotalCount;
            public int TableCount;
            public int ColumnCount;
            public bool Success = true;
        }

        [MenuItem(DDriveMenu.Generate + "Regenerate Tuning Keys")]
        public static void RegenerateMenuItem()
        {
            var result = Regenerate();
            Debug.Log($"[DDrive] Tuning keys regenerated: {result.TotalCount} entries.");
        }

        public static Result Regenerate(TuningTable table = null, string outputPath = DefaultOutputPath)
        {
            table ??= ResolveDefaultTable();
            var result = new Result();

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// D-Drive: 自動生成ファイル。手編集禁止。");
            sb.AppendLine("// D-Drive/Tools/Generate/Regenerate Tuning Keys から再生成される。");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("namespace DDrive.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    public static class TUNING");
            sb.AppendLine("    {");

            if (table != null && table.Entries != null)
            {
                var usedNames = new HashSet<string>();
                var sortedKeys = new List<string>();
                foreach (var entry in table.Entries)
                {
                    if (!string.IsNullOrEmpty(entry.Key))
                    {
                        sortedKeys.Add(entry.Key);
                    }
                }

                sortedKeys.Sort(StringComparer.Ordinal);

                foreach (var key in sortedKeys)
                {
                    var constName = ToConstantName(key);
                    if (!usedNames.Add(constName))
                    {
                        continue; // 重複キーは SpecSheetParser 側で衝突として検出済みのため、生成側では単に無視する
                    }

                    sb.AppendLine($"        public const string {constName} = \"{key}\";");
                    result.TotalCount++;
                }
            }

            sb.AppendLine("    }");
            sb.AppendLine();

            // W-10(2026-09-14) 追加: テーブル型調整値のキー・列キー定数([32_spec_web.md] §5.1「TuningCodegen
            // を拡張: テーブルキーも TUNING 定数として出力する」)。列キーは複数テーブルで同じ名前
            // (例: "Hp")が使われ得るため、テーブル名を頭に付けて一意にする(TUNING_COLUMN.EnemyParamsHp)。
            sb.AppendLine("    public static class TUNING_TABLE");
            sb.AppendLine("    {");
            var tableConstNames = new HashSet<string>();
            var sortedTableKeys = new List<string>();
            if (table != null && table.Tables != null)
            {
                foreach (var tableEntry in table.Tables)
                {
                    if (!string.IsNullOrEmpty(tableEntry.Key))
                    {
                        sortedTableKeys.Add(tableEntry.Key);
                    }
                }
            }

            sortedTableKeys.Sort(StringComparer.Ordinal);
            foreach (var key in sortedTableKeys)
            {
                var constName = ToConstantName(key);
                if (!tableConstNames.Add(constName))
                {
                    continue;
                }

                sb.AppendLine($"        public const string {constName} = \"{key}\";");
                result.TableCount++;
            }

            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine("    public static class TUNING_COLUMN");
            sb.AppendLine("    {");
            var columnConstNames = new HashSet<string>();
            var sortedColumnEntries = new List<(string tableKey, string columnKey)>();
            if (table != null && table.Tables != null)
            {
                foreach (var tableEntry in table.Tables)
                {
                    if (string.IsNullOrEmpty(tableEntry.Key) || tableEntry.Columns == null)
                    {
                        continue;
                    }

                    foreach (var column in tableEntry.Columns)
                    {
                        if (!string.IsNullOrEmpty(column.Key))
                        {
                            sortedColumnEntries.Add((tableEntry.Key, column.Key));
                        }
                    }
                }
            }

            sortedColumnEntries.Sort((a, b) =>
            {
                var byTable = string.CompareOrdinal(a.tableKey, b.tableKey);
                return byTable != 0 ? byTable : string.CompareOrdinal(a.columnKey, b.columnKey);
            });

            foreach (var (tableKey, columnKey) in sortedColumnEntries)
            {
                var constName = ToConstantName(tableKey) + ToConstantName(columnKey);
                if (!columnConstNames.Add(constName))
                {
                    continue;
                }

                sb.AppendLine($"        public const string {constName} = \"{columnKey}\";");
                result.ColumnCount++;
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            // 2026-09-17(docs/41_phase6_review_2026-09-17.md P1-2 (d)) — 安全弁。
            // 定数が 1 つも無い状態で、既存の生成ファイルに定数があるときは上書きしない。
            // 仕様書 Web API が `ok:false`(トークン切れ・許可外・レート制限)を返した結果で
            // TuningTable が空になると、ここが `TUNING` を空クラスで書き出し `TUNING.Xxx` を
            // 参照している全コードが一斉にコンパイルエラーになる。上流(SpecSyncService の
            // IsUnusableForApply)でも止めているが、TuningTable を手で空にした場合や別経路からの
            // 呼び出しでも壊れないよう、ここでも警告 + no-op で継続する(CLAUDE.md §0-4)。
            // 意図して全削除したい場合は Assets/Generated/Tuning.g.cs を先に削除してから再生成する。
            if (result.TotalCount + result.TableCount + result.ColumnCount == 0 && ExistingFileHasConstants(outputPath))
            {
                Debug.LogWarning(
                    $"[DDrive] 調整値のキーが 0 件のため '{outputPath}' の再生成を中止しました" +
                    "(既存の定数を残します)。仕様書の取得に失敗している / TuningTable が空になっていないか確認してください。" +
                    "意図した全削除の場合は、先に生成ファイルを削除してから再生成してください。");
                result.Success = false;
                return result;
            }

            var dir = Path.GetDirectoryName(outputPath);
            if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
            {
                Directory.CreateDirectory(dir);
            }

            File.WriteAllText(outputPath, sb.ToString());

            var normalized = outputPath.Replace('\\', '/');
            if (normalized.StartsWith("Assets/"))
            {
                AssetDatabase.ImportAsset(normalized);
            }

            return result;
        }

        // 既存の生成ファイルに `public const string` が 1 つでもあるか(= 消すと参照側が壊れるか)。
        // 読めない場合は「無い」扱いにして通常の書き出しに進む(例外で止めない)。
        private static bool ExistingFileHasConstants(string outputPath)
        {
            try
            {
                if (!File.Exists(outputPath))
                {
                    return false;
                }

                return File.ReadAllText(outputPath).IndexOf("public const string", StringComparison.Ordinal) >= 0;
            }
            catch (Exception e)
            {
                Debug.LogWarning($"[DDrive] 既存の '{outputPath}' を読めませんでした: {e.Message}");
                return false;
            }
        }

        private static TuningTable ResolveDefaultTable()
        {
            var settings = DDriveSpecSettings.Load();
            if (settings != null && settings.TuningTable != null)
            {
                return settings.TuningTable;
            }

            return AssetDatabase.LoadAssetAtPath<TuningTable>(DDriveSpecSettings.DefaultTuningTablePath);
        }

        // 2026-09-17([41] P2-10) — private だったため SpecWebSender が同じ規則を複製しており、
        // しかも複製側は `char.IsLetterOrDigit`(Unicode)で日本語を残す実装になっていて初版から
        // 不一致だった(`敵/HP` が `HP` と `敵HP` に分かれ、使われているキーが「未使用」として
        // Web に送られていた)。定数名の規則はこの 1 箇所だけに置く。
        internal static string ToConstantName(string key)
        {
            var tokens = key.Split(new[] { '/', '_', '-', ' ' }, StringSplitOptions.RemoveEmptyEntries);
            var sb = new StringBuilder();
            foreach (var token in tokens)
            {
                var clean = SanitizeToken(token);
                if (clean.Length == 0)
                {
                    continue;
                }

                sb.Append(char.ToUpperInvariant(clean[0]));
                if (clean.Length > 1)
                {
                    sb.Append(clean.Substring(1));
                }
            }

            if (sb.Length == 0)
            {
                sb.Append("Unnamed");
            }

            if (!char.IsLetter(sb[0]))
            {
                sb.Insert(0, '_');
            }

            return sb.ToString();
        }

        private static string SanitizeToken(string token)
        {
            var sb = new StringBuilder(token.Length);
            foreach (var c in token)
            {
                if (c is >= 'A' and <= 'Z' or >= 'a' and <= 'z' or >= '0' and <= '9')
                {
                    sb.Append(c);
                }
            }

            return sb.ToString();
        }
    }
}
